_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.10
            "5": 0.19.10
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.10
            "13": windows-amd64
batch_size:
    value: 8
epochs:
    value: 20
image_size:
    value: 128
learning_rate:
    value: 0.001
